spring:
  profiles: dev
  cloud :
    stream:
      kafka: 
        binder: 
          brokers : localhost
          defaultBrokerPort: 9092
          zkNodes: localhost
          defaultZkPort: 2182
          offsetUpdateTimeWindow: 0
          offsetUpdateCount: 0
        autoCreateTopics: true
        autoAddPartitions: true
    bindings:
        output: 
          destination: test2
