spring:
  profiles: development
  cloud :
    stream:
      kafka: 
        binder: 
          brokers : localhost
          defaultBrokerPort: 9092
          zkNodes: localhost
          defaultZkPort: 2181
          offsetUpdateTimeWindow: 0
          offsetUpdateCount: 0
          
      bindings:
          createBuddyEvent:
             destination: createBuddyEvent
            