spring:
  profiles: dev
  cloud :
    stream:
      kafka: 
        binder: 
          brokers : localhost
          defaultBrokerPort: 9092
          zkNodes: localhost
          defaultZkPort: 2181
          offsetUpdateTimeWindow: 0
          offsetUpdateCount: 0
          configuration.topic: test
        autoCreateTopics: false
        autoAddPartitions: true
        
        bindings:
          producer: 
             configuration.topic: test
          
 
