server:
  port : 9001
spring:
  profiles: development
  cloud :
    stream:
      kafka: 
        binder: 
          brokers : 192.168.1.72
          defaultBrokerPort: 9092
          zkNodes: 192.168.1.72
          defaultZkPort: 2181
          offsetUpdateTimeWindow: 0
          offsetUpdateCount: 0
          
      bindings:
          input:
             destination: eventdata
            