server:
  port: 9002
spring:
  profiles: dev,cloud
  cloud :
    stream:
      kafka: 
        binder: 
          brokers : 192.168.1.72
          defaultBrokerPort: 9092
          zkNodes: 192.168.1.72
          defaultZkPort: 2181
          offsetUpdateTimeWindow: 0
          offsetUpdateCount: 0
        autoCreateTopics: true
        autoAddPartitions: true
    
      bindings:
          output:
             destination: eventdata
             content-type: application/json  
